easy_admin:
    entities:
        Etudiant:
            class: App\Entity\Etudiant
        Administrateur:
            class: App\Entity\Administrateur
        Classe:
            class: App\Entity\Classe
        Absence:
            class: App\Entity\Absence
        Exam:
            class: App\Entity\Exam
        Matiere:
            class: App\Entity\Matiere
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', label: 'Image' }
                    - alt
            form:
                fields:
                    - { property: 'file', type: 'Vich\UploaderBundle\Form\Type\VichFileType' }
        Quiz:
            class: App\Entity\Quiz
        Question:
            class: App\Entity\Question

